### ISSUE TITLE
Make Spot Header Images Selectable

### ISSUE THREAD

**Issue by nicnocquee** [ay8s/ShutterSpots-Issues#10]
Probably it's better to be able to tap and show photos and the map  full screen.

![jpeg image-0f6357a74537-1](https://cloud.githubusercontent.com/assets/311343/7195043/679d255c-e4f4-11e4-96ca-d3273e0f4108.jpeg)

**Comment by ay8s** [comment]
Thanks @nicnocquee. Got to add that functionality in :+1: Great validation that it should do that!

**Comment by ay8s** [comment]
Fixed for v1.0. Main header image will be selectable in v1.1.

**Comment by ay8s** [comment]
Adjusted the app in v1.2 to use all the images in the header and are all tappable.
