### ISSUE TITLE
App opens up on 0,0 lat/long instead of current location

### ISSUE THREAD

**Issue by tommoor** [ay8s/ShutterSpots-Issues#20]
Introduced in the latest build, 0.6

**Comment by ay8s** [comment]
Does latest version resolve this @tommoor?

Thanks :)

**Comment by tommoor** [comment]
Fixed, yep.

On Tue, Apr 21, 2015 at 8:09 PM, Andrew Yates <notifications@github.com>
wrote:

> Does latest version resolve this @tommoor <https://github.com/tommoor>?
>
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ay8s/ShutterSpots-Issues/issues/20#issuecomment-95010793>
> .
>



-- 
Tom Moor

http://tommoor.com
http://twitter.com/tommoor
