### ISSUE TITLE
Map on add spot view keeps defaulting back to current location

### ISSUE THREAD

**Issue by tommoor** [ay8s/ShutterSpots-Issues#5]
- Add a new spot view
- Set a pin location different from where you currently are
- Tap on 'add spot'
- Return back to the map view to adjust
- The pin has been reset to your current location

**Comment by ay8s** [comment]
Does this happen with the latest build also @tommoor?

**Comment by tommoor** [comment]
It does indeed

**Comment by ay8s** [comment]
This should be fixed up @tommoor!
