### ISSUE TITLE
After adding a spot it doesn't show up in 'your spots' without a refresh

### ISSUE THREAD

**Issue by tommoor** [ay8s/ShutterSpots-Issues#6]
- Add a new spot
- Go to 'your spots' view from the bottom bar
- New spot does not appear in list

I'd expect the new spot to be here without requiring a manual refresh

**Comment by nicnocquee** [comment]
+1 to this. it also should appear in Nearby immediately.

**Comment by ay8s** [comment]
Fixed for next build! Thanks @tommoor @nicnocquee :+1:
