### ISSUE TITLE
Add option to select image when adding a spot.

### ISSUE THREAD

**Issue by tommoor** [ay8s/ShutterSpots-Issues#7]
It would be great to be able to select a photo that best represents the spot at creation. Right now it appears to pick a random picture which isn't always great.

You could also potentially pick out meta data from the chosen picture to automatically guess at other aspects of the form, for example the category.

**Comment by ay8s** [comment]
Good one, might include this in the next version. Right now it grabs the first photo from Flickr and uses that. Can see it returning odd photos in some cases.

**Comment by aajhiggs** [comment]
+1 - the photo I got was not the best representation of what I was trying to convey from the spot (although it was still a good photo)

**Comment by ay8s** [comment]
This is added as on the most recent build. A future build will try and grab the exif data and use the location if present to populate the location.
