### ISSUE TITLE
Crash when going back to Nearby

### ISSUE THREAD

**Issue by nicnocquee** [ay8s/ShutterSpots-Issues#9]
How to reproduce:

1. Select a spot in Nearby.
2. Scroll down in the Spot page.
3. Go back to nearby.
4. Boom.

**Comment by nicnocquee** [comment]
Actually, it happens not when going back to Nearby. It always happens when going back _from_ the Spot page. Also happens in Search page, tap on pin, tap on Info button.

**Comment by ay8s** [comment]
Pretty sure this is fixed up. Thanks @nicnocquee :+1:

**Comment by ay8s** [comment]
Closing for now as likely fixed in upcoming build.
